name: monie_conv
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
